//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmCustomer
    {
        public CrmCustomer()
        {
            this.CrmEmailTrackings = new HashSet<CrmEmailTracking>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid GuidGroup { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string Sex { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string LinkFacebook { get; set; }
        public string Picture { get; set; }
        public string Location { get; set; }
        public string UID { get; set; }
        public string Job { get; set; }
    
        public virtual CrmCustomerGroup CrmCustomerGroup { get; set; }
        public virtual ICollection<CrmEmailTracking> CrmEmailTrackings { get; set; }
    }
}
