//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmEmailCampaign
    {
        public CrmEmailCampaign()
        {
            this.CrmEmailTrackings = new HashSet<CrmEmailTracking>();
            this.MapCampaignSettings = new HashSet<MapCampaignSetting>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public System.Guid GuidEmailSetting { get; set; }
        public System.Guid GuidEmailTemplate { get; set; }
        public System.Guid GuidCustomerGroup { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsBcc { get; set; }
        public bool IsCc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Status { get; set; }
    
        public virtual CrmEmailTemplate CrmEmailTemplate { get; set; }
        public virtual ICollection<CrmEmailTracking> CrmEmailTrackings { get; set; }
        public virtual ICollection<MapCampaignSetting> MapCampaignSettings { get; set; }
    }
}
