//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmEmailTracking
    {
        public System.Guid Guid { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid GuidCustomer { get; set; }
        public System.Guid GuidCampaign { get; set; }
        public System.DateTime OpentAt { get; set; }
        public int TimesOpen { get; set; }
    
        public virtual CrmCustomer CrmCustomer { get; set; }
        public virtual CrmEmailCampaign CrmEmailCampaign { get; set; }
    }
}
