//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosProduce
    {
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> GuidPartner { get; set; }
        public System.Guid GuidCategory { get; set; }
        public int Amount { get; set; }
        public string GuidTags { get; set; }
        public Nullable<decimal> SaleOffPrice { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoFriendUrl { get; set; }
        public int Sort { get; set; }
        public bool TopProduce { get; set; }
        public bool HotProduce { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Status { get; set; }
        public string FullAddress { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> ApprovedStatus { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<int> Legit { get; set; }
        public Nullable<int> LegitCount { get; set; }
    }
}
